services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./data:/data
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - 7575:7575
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
