services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5003:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    environment:
      PUID: $PUID
      PGID: $PGID
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
