services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --http-api-metrics
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - reverse_proxy

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus/
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - reverse_proxy

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 127.0.0.1:3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    networks:
      - reverse_proxy

volumes:
  prometheus:
  grafana:

networks:
  reverse_proxy:
    external: true
