---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

# - Group:
#     - Service:
#         icon: example.svg
#         href: https://example.localhost/
#         description: Description example
